#!/bin/bash

red="\033[31m"
yellow="\033[33m"
green="\033[32m"
endColor="\033[97m"
check="✔"
cross="✘"

NODE_VERSION="12.16.1"

set -e

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

echo -e "${yellow}=> Installing Node: $NODE_VERSION${endColor}"
cd ~/
wget "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-armv7l.tar.xz"
tar -xf node-v$NODE_VERSION-linux-armv7l.tar.xz
sudo ln -sfv ~/node-v$NODE_VERSION-linux-armv7l/bin/node /usr/local/bin/node
sudo ln -sfv ~/node-v$NODE_VERSION-linux-armv7l/bin/npm /usr/local/bin/npm
sudo ln -sfv ~/node-v$NODE_VERSION-linux-armv7l/bin/npx /usr/local/bin/npx

echo -e "${green}=> Done${endColor}"
