#!/bin/bash

source ./colors

set -e

if [[ $EUID -ne 0 ]]; then
  echo -e "[Node Installer]\tThis script must be run as root"
  exit 1
fi

cd ~/
NODE_VERSION=12.14.1
NODE_ARCH=
case "$(dpkg --print-architecture)" in
  "amd64")
    NODE_ARCH="x64"
    ;;
  "armv7l")
    NODE_ARCH="armv7l"
    ;;
  *)
    echo -e "${red}=> Script not able to install Node on this architecture: $(dpkg --print-architecture)"
    exit 1
esac

echo -e "${yellow}=> Installing Node$NODE_VERSION-$NODE_ARCH:${endColor}\r"
wget "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-$NODE_ARCH.tar.xz"
tar -xf node-v$NODE_VERSION-linux-$NODE_ARCH.tar.xz
sudo ln -s ~/node-v$NODE_VERSION-linux-$NODE_ARCH/bin/node /usr/local/bin/node
sudo ln -s ~/node-v$NODE_VERSION-linux-$NODE_ARCH/bin/npm /usr/local/bin/npm
sudo ln -s ~/node-v$NODE_VERSION-linux-$NODE_ARCH/bin/npx /usr/local/bin/npx
