#!/bin/bash

set -e

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

apt-get update

apt-get install -y \
  build-essential \
  git \
  gnome-schedule \
  libc6-dev \
  libncursesw5-dev \
  libreadline-gplv2-dev \
  libssl-dev \
  libgdbm-dev \
  libsqlite3-dev \
  libbz2-dev \
  python \
  python-dev \
  python-pip \
  python3 \
  python3-dev \
  python3-pip \
  tk-dev

pip install virtualenv

