#!/bin/bash

red="\033[31m"
yellow="\033[33m"
green="\033[32m"
endColor="\033[97m"
check="✔"
cross="✘"

PYTHON_VERSION=${PYTHON_VERSION:-'3.6.8'}
PYTHON='python3.6'
PYTHON_SRC='python-src'
PYTHON_ZIP="Python-$PYTHON_VERSION.tgz"
PYTHON_PATH="/usr/local/bin/$PYTHON"

set -e

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 
  exit 1
fi

# LINUX DEPENDENCIES

apt-get update

apt-get install -y \
  build-essential \
  git \
  gnome-schedule \
  libc6-dev \
  libncursesw5-dev \
  libreadline-gplv2-dev \
  libssl-dev \
  libgdbm-dev \
  libsqlite3-dev \
  libbz2-dev \
  python \
  python-dev \
  python-pip \
  python3 \
  python3-dev \
  python3-pip \
  tk-dev \
  vim

# VIRTUALENV

pip install virtualenv

# COMPILE PYTHON
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"

echo -e "${yellow}=> Installing Python Version\t${green}$PYTHON_VERSION${endColor}"

if [ -d "$PYTHON_SRC" ];
then
	echo -e "${yellow}=> Removing old Python source files${endColor}"
	rm -rf $PYTHON_SRC
fi

echo -e "${yellow}=> Downloading $PYTHON_ZIP${endColor}"
curl -L -O "https://www.python.org/ftp/python/$PYTHON_VERSION/$PYTHON_ZIP"

echo -e "${yellow}=> Unpacking $PYTHON_ZIP${endColor}"
mkdir $PYTHON_SRC
tar -xvzf "$PYTHON_ZIP" -C $PYTHON_SRC --strip-components=2

echo -e "${yellow}=> Compiling Python$PYTHON_VERSION:${endColor}\r"
cd $PYTHON_SRC
./configure --enable-optimizations
make -j4
sudo make install
cd ../

